language: go

go:
  - "1.10"

script:
  - export PATH=$PATH:$PWD/bin
  - curl -L https://git.io/vp6lP | sh
  - gometalinter --vendor --enable=errcheck --enable=vet --enable=deadcode ./...
  - go test ./...
